import Head from 'next/head'
import { Inter } from '@next/font/google'
// import Hero from '@/components/home/Hero'
import Product from '../components/products/Product'
const inter = Inter({ subsets: ['latin'] })
import Hero from '../components/home/Hero'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero/>
        <Product />
      </main>
    </>
  )
}
